---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: monkeys
  - name: stemcell
  - name: release
  - name: director_creds

outputs:
  - name: compiled-release

params:
  BOSH_ENVIRONMENT:
  BOSH_CA_CERT:
  BOSH_CLIENT: admin
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:

run:
  path: monkeys/ci/tasks/export-release.sh
