---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: monkeys
  - name: stemcell
  - name: release
  - name: director-state

outputs:
  - name: compiled-release

params:
  BOSH_DEPLOYMENT:

run:
  path: monkeys/ci/tasks/export-release.sh
