---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfcommunity/monkeys-ci

inputs:
  - name: monkeys

outputs:
  - name: director_creds

params:
  GITHUB_TOKEN:
  VAULT_TARGET:
  VAULT_PREFIX:
