jobs:
- name: upload-stemcell
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: ubuntu-trusty-stemcell
    task: upload-stemcell
  - aggregate:
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-vsphere-esxi.spruce.yml
      put: compiled-stemcell-vsphere-esxi-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-vsphere-esxi.patch.yml
      put: compiled-stemcell-vsphere-esxi-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-warden-boshlite.spruce.yml
      put: compiled-stemcell-warden-boshlite-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-warden-boshlite.patch.yml
      put: compiled-stemcell-warden-boshlite-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-aws-xen-hvm.spruce.yml
      put: compiled-stemcell-aws-xen-hvm-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-aws-xen-hvm.patch.yml
      put: compiled-stemcell-aws-xen-hvm-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-azure-hyperv.spruce.yml
      put: compiled-stemcell-azure-hyperv-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-azure-hyperv.patch.yml
      put: compiled-stemcell-azure-hyperv-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-google-kvm.spruce.yml
      put: compiled-stemcell-google-kvm-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-google-kvm.patch.yml
      put: compiled-stemcell-google-kvm-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-openstack-kvm.spruce.yml
      put: compiled-stemcell-openstack-kvm-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-openstack-kvm.patch.yml
      put: compiled-stemcell-openstack-kvm-patch
  public: false
  serial: true
- name: build-task-image
  plan:
  - get: monkeys
  - params:
      build: monkeys/ci/image
    put: ci-image
  serial: true
- name: bosh-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: bosh-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: bosh-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: bosh-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
      RELEASE_ORG_NAME: cloudfoundry/bosh
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/bosh*.tgz
      put: bosh-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/bosh*-latest.spruce.yml
      put: bosh-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/bosh*-latest.patch.yml
      put: bosh-release-compiled-release-patch-yml
  serial: true
- name: cf-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: cf-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: cf-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: cf-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
      RELEASE_ORG_NAME: cloudfoundry/cf-release
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/cf-release*.tgz
      put: cf-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/cf-release*-latest.spruce.yml
      put: cf-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/cf-release*-latest.patch.yml
      put: cf-release-compiled-release-patch-yml
  serial: true
- name: credhub-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: credhub-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: credhub-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: credhub-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
      RELEASE_ORG_NAME: pivotal-cf/credhub-release
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/pivotal-cf/credhub-release*.tgz
      put: credhub-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/pivotal-cf/credhub-release*-latest.spruce.yml
      put: credhub-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/pivotal-cf/credhub-release*-latest.patch.yml
      put: credhub-release-compiled-release-patch-yml
  serial: true
- name: stannis-boshrelease
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: stannis-boshrelease
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: stannis-boshrelease
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: stannis-boshrelease
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
      RELEASE_ORG_NAME: cloudfoundry-community/stannis-boshrelease
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry-community/stannis-boshrelease*.tgz
      put: stannis-boshrelease-compiled-release
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry-community/stannis-boshrelease*-latest.spruce.yml
      put: stannis-boshrelease-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry-community/stannis-boshrelease*-latest.patch.yml
      put: stannis-boshrelease-compiled-release-patch-yml
  serial: true
- name: uaa-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: uaa-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: uaa-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: uaa-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
      RELEASE_ORG_NAME: cloudfoundry/uaa-release
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/uaa-release*.tgz
      put: uaa-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/uaa-release*-latest.spruce.yml
      put: uaa-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/cloudfoundry/uaa-release*-latest.patch.yml
      put: uaa-release-compiled-release-patch-yml
  serial: true
release:
  release_label: uaa-release
  release_org_name: cloudfoundry/uaa-release
resources:
- name: monkeys
  source:
    uri: https://github.com/cloudfoundry-community/million-monkeys.git
  type: git
- name: ubuntu-trusty-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version_family: latest
  type: bosh-io-stemcell
- name: ci-image
  source:
    email: {{docker-hub-email}}
    password: {{docker-hub-password}}
    repository: cfcommunity/monkeys-ci
    username: {{docker-hub-username}}
  type: docker-image
- name: bosh-release
  source:
    repository: cloudfoundry/bosh
  type: bosh-io-release
- name: bosh-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: cloudfoundry/bosh-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: bosh-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry/bosh-latest.spruce.yml
  type: s3
- name: bosh-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry/bosh-latest.patch.yml
  type: s3
- name: cf-release
  source:
    repository: cloudfoundry/cf-release
  type: bosh-io-release
- name: cf-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: cloudfoundry/cf-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: cf-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry/cf-release-latest.spruce.yml
  type: s3
- name: cf-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry/cf-release-latest.patch.yml
  type: s3
- name: credhub-release
  source:
    access_token: {{GITHUB_TOKEN}}
    pre_release: true
    repository: credhub-release
    user: pivotal-cf
  type: github-release
- name: credhub-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: pivotal-cf/credhub-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: credhub-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: pivotal-cf/credhub-release-latest.spruce.yml
  type: s3
- name: credhub-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: pivotal-cf/credhub-release-latest.patch.yml
  type: s3
- name: stannis-boshrelease
  source:
    repository: cloudfoundry-community/stannis-boshrelease
  type: bosh-io-release
- name: stannis-boshrelease-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: cloudfoundry-community/stannis-boshrelease-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: stannis-boshrelease-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry-community/stannis-boshrelease-latest.spruce.yml
  type: s3
- name: stannis-boshrelease-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry-community/stannis-boshrelease-latest.patch.yml
  type: s3
- name: uaa-release
  source:
    repository: cloudfoundry/uaa-release
  type: bosh-io-release
- name: uaa-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: cloudfoundry/uaa-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: uaa-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry/uaa-release-latest.spruce.yml
  type: s3
- name: uaa-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cloudfoundry/uaa-release-latest.patch.yml
  type: s3
- name: compiled-stemcell-vsphere-esxi-spruce
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-vsphere-esxi.spruce.yml
  type: s3
- name: compiled-stemcell-vsphere-esxi-patch
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-vsphere-esxi.patch.yml
  type: s3
- name: compiled-stemcell-warden-boshlite-spruce
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-warden-boshlite.spruce.yml
  type: s3
- name: compiled-stemcell-warden-boshlite-patch
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-warden-boshlite.patch.yml
  type: s3
- name: compiled-stemcell-aws-xen-hvm-spruce
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-aws-xen-hvm.spruce.yml
  type: s3
- name: compiled-stemcell-aws-xen-hvm-patch
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-aws-xen-hvm.patch.yml
  type: s3
- name: compiled-stemcell-azure-hyperv-spruce
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-azure-hyperv.spruce.yml
  type: s3
- name: compiled-stemcell-azure-hyperv-patch
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-azure-hyperv.patch.yml
  type: s3
- name: compiled-stemcell-google-kvm-spruce
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-google-kvm.spruce.yml
  type: s3
- name: compiled-stemcell-google-kvm-patch
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-google-kvm.patch.yml
  type: s3
- name: compiled-stemcell-openstack-kvm-spruce
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-openstack-kvm.spruce.yml
  type: s3
- name: compiled-stemcell-openstack-kvm-patch
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stemcell-openstack-kvm.patch.yml
  type: s3
uploads:
- name: vsphere-esxi
  puts:
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-vsphere-esxi.spruce.yml
    put: compiled-stemcell-vsphere-esxi-spruce
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-vsphere-esxi.patch.yml
    put: compiled-stemcell-vsphere-esxi-patch
- name: warden-boshlite
  puts:
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-warden-boshlite.spruce.yml
    put: compiled-stemcell-warden-boshlite-spruce
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-warden-boshlite.patch.yml
    put: compiled-stemcell-warden-boshlite-patch
- name: aws-xen-hvm
  puts:
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-aws-xen-hvm.spruce.yml
    put: compiled-stemcell-aws-xen-hvm-spruce
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-aws-xen-hvm.patch.yml
    put: compiled-stemcell-aws-xen-hvm-patch
- name: azure-hyperv
  puts:
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-azure-hyperv.spruce.yml
    put: compiled-stemcell-azure-hyperv-spruce
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-azure-hyperv.patch.yml
    put: compiled-stemcell-azure-hyperv-patch
- name: google-kvm
  puts:
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-google-kvm.spruce.yml
    put: compiled-stemcell-google-kvm-spruce
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-google-kvm.patch.yml
    put: compiled-stemcell-google-kvm-patch
- name: openstack-kvm
  puts:
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-openstack-kvm.spruce.yml
    put: compiled-stemcell-openstack-kvm-spruce
  - params:
      acl: public-read
      file: compiled-stemcell/stemcell-openstack-kvm.patch.yml
    put: compiled-stemcell-openstack-kvm-patch

