jobs:
- name: upload-stemcell
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: ubuntu-trusty-stemcell
    task: upload-stemcell
  public: false
  serial: true
- name: build-task-image
  plan:
  - get: monkeys
  - params:
      build: monkeys/ci/image
    put: ci-image
  serial: true
- name: bosh-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: bosh-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: bosh-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: bosh-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/*.tgz
      put: bosh-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/*-latest.spruce.yml
      put: bosh-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/*-latest.patch.yml
      put: bosh-release-compiled-release-patch-yml
  serial: true
- name: cf-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: cf-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: cf-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: cf-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/*.tgz
      put: cf-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/*-latest.spruce.yml
      put: cf-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/*-latest.patch.yml
      put: cf-release-compiled-release-patch-yml
  serial: true
- name: credhub-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: credhub-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: credhub-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: credhub-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/*.tgz
      put: credhub-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/*-latest.spruce.yml
      put: credhub-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/*-latest.patch.yml
      put: credhub-release-compiled-release-patch-yml
  serial: true
- name: stannis-boshrelease
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: stannis-boshrelease
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: stannis-boshrelease
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: stannis-boshrelease
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/*.tgz
      put: stannis-boshrelease-compiled-release
    - params:
        acl: public-read
        file: compiled-release/*-latest.spruce.yml
      put: stannis-boshrelease-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/*-latest.patch.yml
      put: stannis-boshrelease-compiled-release-patch-yml
  serial: true
- name: uaa-release
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params:
        tarball: false
      passed:
      - upload-stemcell
      trigger: true
    - get: uaa-release
      trigger: true
  - file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: {{GITHUB_TOKEN}}
      VAULT_ADDR: {{VAULT_ADDR}}
      VAULT_PREFIX: {{VAULT_PREFIX}}
      VAULT_SKIP_VERIFY: 1
    task: director-creds
  - file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      release: uaa-release
      stemcell: ubuntu-trusty-stemcell
    params:
      BOSH_DEPLOYMENT: uaa-release
      BUCKET_URL: https://s3.amazonaws.com/million-monkeys-releases
    task: export-release
  - aggregate:
    - params:
        acl: public-read
        file: compiled-release/*.tgz
      put: uaa-release-compiled-release
    - params:
        acl: public-read
        file: compiled-release/*-latest.spruce.yml
      put: uaa-release-compiled-release-yml
    - params:
        acl: public-read
        file: compiled-release/*-latest.patch.yml
      put: uaa-release-compiled-release-patch-yml
  serial: true
release:
  release_label: uaa-release
  release_org_name: cloudfoundry/uaa-release
resources:
- name: monkeys
  source:
    uri: https://github.com/cloudfoundry-community/million-monkeys.git
  type: git
- name: ubuntu-trusty-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version_family: latest
  type: bosh-io-stemcell
- name: ci-image
  source:
    email: {{docker-hub-email}}
    password: {{docker-hub-password}}
    repository: cfcommunity/monkeys-ci
    username: {{docker-hub-username}}
  type: docker-image
- name: bosh-release
  source:
    repository: cloudfoundry/bosh
  type: bosh-io-release
- name: bosh-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: bosh-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: bosh-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: bosh-release-latest.spruce.yml
  type: s3
- name: bosh-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: bosh-release-latest.patch.yml
  type: s3
- name: cf-release
  source:
    repository: cloudfoundry/cf-release
  type: bosh-io-release
- name: cf-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: cf-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: cf-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cf-release-latest.spruce.yml
  type: s3
- name: cf-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: cf-release-latest.patch.yml
  type: s3
- name: credhub-release
  source:
    access_token: {{GITHUB_TOKEN}}
    pre_release: true
    repository: credhub-release
    user: pivotal-cf
  type: github-release
- name: credhub-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: credhub-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: credhub-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: credhub-release-latest.spruce.yml
  type: s3
- name: credhub-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: credhub-release-latest.patch.yml
  type: s3
- name: stannis-boshrelease
  source:
    repository: cloudfoundry-community/stannis-boshrelease
  type: bosh-io-release
- name: stannis-boshrelease-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: stannis-boshrelease-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: stannis-boshrelease-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stannis-boshrelease-latest.spruce.yml
  type: s3
- name: stannis-boshrelease-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: stannis-boshrelease-latest.patch.yml
  type: s3
- name: uaa-release
  source:
    repository: cloudfoundry/uaa-release
  type: bosh-io-release
- name: uaa-release-compiled-release
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases
    regexp: uaa-release-([\d\.]+)-ubuntu-trusty-[\d\.]+.tgz
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
  type: s3
- name: uaa-release-compiled-release-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: uaa-release-latest.spruce.yml
  type: s3
- name: uaa-release-compiled-release-patch-yml
  source:
    access_key_id: {{cfcommunity-aws-access}}
    bucket: million-monkeys-releases-latest
    region_name: us-east-1
    secret_access_key: {{cfcommunity-aws-secret}}
    versioned_file: uaa-release-latest.patch.yml
  type: s3

