---
resources:
- name: monkeys
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/million-monkeys.git

- name: ubuntu-trusty-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version_family: latest

- name: stannis-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/stannis-boshrelease

- name: ci-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: cfcommunity/monkeys-ci

jobs:
- name: upload-stemcell
  public: true
  serial: true
  plan:
  - get: ubuntu-trusty-stemcell

- name: stannis-boshrelease
  public: true
  serial: true
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
      params: {tarball: false}
    - get: stannis-boshrelease
  - task: export-release
    file: monkeys/ci/tasks/export-release.yml
    input_mapping:
      stemcell: ubuntu-trusty-stemcell
      release: stannis-boshrelease
    params:
      BOSH_DEPLOYMENT: stannis-compilation
      BOSH_ENVIRONMENT: {{BOSH_ENVIRONMENT}}
      BOSH_CA_CERT: {{BOSH_CA_CERT}}
      BOSH_CLIENT: {{BOSH_CLIENT}}
      BOSH_CLIENT_SECRET: {{BOSH_CLIENT_SECRET}}

- name: build-task-image
  serial: true
  plan:
  - get: monkeys
  - put: ci-image
    params:
      build: monkeys/ci/image
