---
resources:
- name: monkeys
  type: git
  source:
    uri: https://github.com/cloudfoundry-community/million-monkeys.git

- name: ubuntu-trusty-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version_family: latest

- name: ci-image
  type: docker-image
  source:
    email: (( grab meta.docker_hub.email ))
    username: (( grab meta.docker_hub.username ))
    password: (( grab meta.docker_hub.password ))
    repository: cfcommunity/monkeys-ci

jobs:
- name: upload-stemcell
  public: false
  serial: true
  plan:
  - aggregate:
    - get: monkeys
    - get: ubuntu-trusty-stemcell
  - task: director-creds
    file: monkeys/ci/tasks/director-creds.yml
    params:
      GITHUB_TOKEN: (( grab meta.github.token ))
      VAULT_ADDR: (( grab meta.vault.addr ))
      VAULT_SKIP_VERIFY: 1
      VAULT_PREFIX: (( grab meta.vault.prefix ))
  - task: upload-stemcell
    file: monkeys/ci/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: ubuntu-trusty-stemcell
  - aggregate:
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-vsphere-esxi.spruce.yml
      put: compiled-stemcell-vsphere-esxi-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-vsphere-esxi.patch.yml
      put: compiled-stemcell-vsphere-esxi-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-warden-boshlite.spruce.yml
      put: compiled-stemcell-warden-boshlite-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-warden-boshlite.patch.yml
      put: compiled-stemcell-warden-boshlite-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-aws-xen-hvm.spruce.yml
      put: compiled-stemcell-aws-xen-hvm-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-aws-xen-hvm.patch.yml
      put: compiled-stemcell-aws-xen-hvm-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-azure-hyperv.spruce.yml
      put: compiled-stemcell-azure-hyperv-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-azure-hyperv.patch.yml
      put: compiled-stemcell-azure-hyperv-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-google-kvm.spruce.yml
      put: compiled-stemcell-google-kvm-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-google-kvm.patch.yml
      put: compiled-stemcell-google-kvm-patch
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-openstack-kvm.spruce.yml
      put: compiled-stemcell-openstack-kvm-spruce
    - params:
        acl: public-read
        file: compiled-stemcell/stemcell-openstack-kvm.patch.yml
      put: compiled-stemcell-openstack-kvm-patch


- name: build-task-image
  serial: true
  plan:
  - get: monkeys
  - put: ci-image
    params:
      build: monkeys/ci/image
